# Generated by Django 4.1.7 on 2024-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'permissions': [('has_score_permission', 'User has Score permission')]},
        ),
    ]
