# Generated by Django 4.2 on 2023-12-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0005_alter_category_options_alter_brand_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
