# Generated by Django 4.1.7 on 2024-01-06 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_product_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='parent',
            new_name='Parent',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
    ]
